# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080

spring:
  # jackson 相关配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///no263_book_shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    chain.strategy.content.enabled: true
    chain.strategy.content.paths: /**

mybatis:
  mapper-locations: classpath*:/mapper/**.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  typeAliasesPackage: com.gimiii.server.mall.model  #这里是实体类的位置 多个package用逗号或者分号分隔
  configuration:
    lazyLoadingEnabled: false #延时加载的开关
    log-impl: com.beauty.config.GimiiiStdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true


# 文件存储路径
file:
  linux:
    path: /home/book/file/
  windows:
    path: C:\home\book\file\
  url: http://127.0.0.1:8080/
  maxSize: 10

